logging.level.org.springframework.jdbc.datasource.init.ScriptUtils: debug
spring:
  h2.console.enabled: true
  datasource.url: jdbc:h2:mem:testdb

sensor:
  thresholds:
    warnLevel: 2000
    times: 3
